BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
ADMIN_IDS = [123456789]  # Ваш Telegram ID

# Настройки Platega.io
PLATEGA_MERCHANT_ID = "YOUR_PLATEGA_MERCHANT_UUID"
PLATEGA_SECRET_KEY = "YOUR_PLATEGA_SECRET_KEY"

# Настройки CryptoBot (от @CryptoBot)
CRYPTO_BOT_TOKEN = "YOUR_CRYPTO_BOT_API_TOKEN"
